services:
  - type: web
    name: telegram-faq-bot
    env: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: PORT
        value: 8080
      - key: GOOGLE_SHEET_URL
        sync: false